@vite(['resources/js/app.js'])
@vite(['resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js', 'resources/assets/vendor/js/menu.js'])
@yield('vendor-script')
@vite(['resources/assets/js/main.js'])
@yield('page-script')